/**
 * All user-facing UI text lives here, grouped by key and language, so
 * translations can be reviewed and completed in one place. Bengali and Hindi
 * cover navigation, forms, validation messages and status labels.
 *
 * Anything missing from bn/hi falls back to English at runtime (see i18n.tsx).
 */
const en = {
  'app.name': 'DukaanSaathi',
  'app.tagline': 'Your store, in every language.',
  'app.languageLabel': 'Language',
  'app.chooseLanguage': 'Choose your language',
  'app.skipToContent': 'Skip to main content',

  'nav.explore': 'Explore',
  'nav.orders': 'Orders',
  'nav.account': 'Account',
  'nav.overview': 'Overview',
  'nav.products': 'Products',
  'nav.business': 'Business',
  'nav.conversations': 'Conversations',
  'nav.reviews': 'Reviews',
  'nav.signOut': 'Sign out',
  'nav.signIn': 'Sign in',
  'nav.merchantArea': 'Business dashboard',
  'nav.customerArea': 'Customer area',
  'nav.exploreAsCustomer': 'Explore as a customer',
  'nav.manageBusiness': 'Manage or set up a business',
  'nav.menu': 'Menu',

  'landing.explore': 'Explore as a customer',
  'landing.setUpBusiness': 'Set up my business',
  'landing.customerNote': 'Browse shops and ask questions without an account.',
  'landing.businessNote': 'Create an account to manage your shop, products and orders.',
  'landing.howItWorks': 'How DukaanSaathi works',
  'landing.step1Title': 'Find a nearby shop',
  'landing.step1Body': 'Search by name, category or area across local businesses.',
  'landing.step2Title': 'Ask in your language',
  'landing.step2Body': 'Type or speak in English, Bengali or Hindi and get answers from the shop\u2019s own catalogue.',
  'landing.step3Title': 'Place your order',
  'landing.step3Body': 'Build a cart, review the total and confirm. Sign in with Google to send the order.',
  'landing.forBusinesses': 'For business owners',
  'landing.businessPoint1': 'Publish your catalogue from a spreadsheet',
  'landing.businessPoint2': 'Answer customer questions automatically, in three languages',
  'landing.businessPoint3': 'Track orders and update their status',

  'auth.customerSignIn': 'Customer sign in',
  'auth.customerSignInIntro': 'Sign in with Google to place an order and see your order history.',
  'auth.continueWithGoogle': 'Continue with Google',
  'auth.businessLogin': 'Business login',
  'auth.businessLoginIntro': 'Sign in to manage your shop, products and orders.',
  'auth.createBusinessAccount': 'Create business account',
  'auth.businessSignUpIntro': 'Create an account for your shop. You will add your business details in the next step.',
  'auth.email': 'Email address',
  'auth.password': 'Password',
  'auth.confirmPassword': 'Confirm password',
  'auth.ownerName': 'Your name',
  'auth.newBusinessOwner': 'New business owner?',
  'auth.existingBusinessOwner': 'Already have a business account?',
  'auth.customerBrowsing': 'Just want to browse?',
  'auth.goToExplore': 'Explore shops without an account',
  'auth.checkEmail': 'Check your email to confirm your account, then log in.',
  'auth.signedInAs': 'Signed in as {email}',
  'auth.notConfigured': 'Sign-in is not configured for this deployment yet. Add the Supabase keys to enable it.',
  'auth.googleNotConfigured': 'Google sign-in is not configured yet, so orders cannot be submitted. You can still browse and chat.',
  'auth.whyGoogle': 'Orders need a verified account so the shop can reach you. Browsing and chat stay open to everyone.',
  'auth.passwordMismatch': 'The two passwords do not match.',
  'auth.passwordTooShort': 'Use at least 8 characters.',

  'common.loading': 'Loading\u2026',
  'common.saving': 'Saving\u2026',
  'common.save': 'Save',
  'common.cancel': 'Cancel',
  'common.close': 'Close',
  'common.edit': 'Edit',
  'common.delete': 'Remove',
  'common.archive': 'Archive',
  'common.restore': 'Restore',
  'common.back': 'Back',
  'common.retry': 'Try again',
  'common.search': 'Search',
  'common.filter': 'Filter',
  'common.all': 'All',
  'common.optional': 'optional',
  'common.required': 'Required',
  'common.yes': 'Yes',
  'common.no': 'No',
  'common.confirm': 'Confirm',
  'common.add': 'Add',
  'common.remove': 'Remove',
  'common.download': 'Download',
  'common.upload': 'Upload',
  'common.refresh': 'Refresh',
  'common.notSet': 'Not set',
  'common.unknown': 'Unknown',
  'common.today': 'Today',
  'common.resolved': 'Resolved',
  'common.open': 'Open',
  'common.viewAll': 'View all',
  'common.actions': 'Actions',
  'common.status': 'Status',
  'common.total': 'Total',
  'common.quantity': 'Quantity',
  'common.price': 'Price',
  'common.name': 'Name',
  'common.category': 'Category',
  'common.notes': 'Notes',
  'common.somethingWentWrong': 'Something went wrong.',
  'common.row': 'Row {row}',

  'state.loading': 'Loading\u2026',
  'state.emptyTitle': 'Nothing here yet',
  'state.emptyBusinesses': 'No shops match your search yet. Try another word or category.',
  'state.emptyProducts': 'This shop has not published any products yet.',
  'state.emptyOrders': 'You have not placed any orders yet.',
  'state.emptyMerchantOrders': 'No orders yet. New orders will appear here.',
  'state.emptyConversations': 'No customer questions yet.',
  'state.emptyReviews': 'No reviews yet. Reviews appear after a customer completes an order.',
  'state.errorTitle': 'We could not load this',
  'state.offline': 'The server could not be reached. Check your connection and try again.',

  'explore.title': 'Find a local shop',
  'explore.searchLabel': 'Search shops',
  'explore.searchPlaceholder': 'Shop name, area or category',
  'explore.categoryLabel': 'Category',
  'explore.allShops': 'All shops',
  'explore.recentlyAccessed': 'Recently accessed',
  'explore.resultCount': '{count} shops',
  'explore.openNow': 'Open now',
  'explore.closedNow': 'Closed',
  'explore.hoursUnknown': 'Hours not published',
  'explore.products': '{count} products',

  'business.about': 'About',
  'business.hours': 'Opening hours',
  'business.contact': 'Contact',
  'business.address': 'Address',
  'business.options': 'Pickup and delivery',
  'business.pickup': 'Pickup available',
  'business.delivery': 'Delivery available',
  'business.noPickup': 'Pickup not offered',
  'business.noDelivery': 'Delivery not offered',
  'business.paymentMethods': 'Accepted payment methods',
  'business.paymentNote': 'Shown for information only. DukaanSaathi does not process payments.',
  'business.returnPolicy': 'Return policy',
  'business.faqs': 'Common questions',
  'business.catalog': 'Products',
  'business.catalogSearch': 'Search products',
  'business.quickNav': 'Jump to',
  'business.storeInformation': 'Store information',
  'business.askShop': 'Ask this shop',
  'business.reviews': 'Recent ratings',
  'business.ratingSummary': '{rating} out of 5 from {count} reviews',
  'business.noRating': 'No ratings yet',
  'business.closedToday': 'Closed',

  'product.available': 'Available',
  'product.outOfStock': 'Out of stock',
  'product.unknownAvailability': 'Availability unknown',
  'product.addToCart': 'Add',
  'product.added': 'Added',
  'product.priceUnavailable': 'Ask the shop for the price',

  'chat.title': 'Ask {business}',
  'chat.intro': 'Ask about products, prices, timings or policies. Answers come from what this shop has published.',
  'chat.placeholder': 'Type your question\u2026',
  'chat.send': 'Send',
  'chat.recording': 'Recording\u2026 tap stop when you finish',
  'chat.startRecording': 'Record a voice question',
  'chat.stopRecording': 'Stop recording',
  'chat.transcribing': 'Transcribing your recording\u2026',
  'chat.transcriptReview': 'Check the transcript before sending. You can edit it.',
  'chat.detectedLanguage': 'Detected language: {language}',
  'chat.detectionUnclear': 'We could not detect the spoken language. Pick it below so the answer uses the right voice.',
  'chat.spokenLanguage': 'Language you spoke',
  'chat.useInterfaceLanguage': 'Same as the interface language',
  'chat.chooseLanguage': 'Choose the language you spoke',
  'chat.pickLanguageBeforeSending': 'Choose the language you spoke before sending, so the answer and the voice are correct.',
  'chat.replyLanguage': 'Reply language',
  'chat.detectedFromScript': 'Detected from script: {language}',
  'chat.followInterfaceLanguage': 'Follow the interface language',
  'chat.waitingForReply': 'Waiting for the shop assistant\u2026',
  'chat.sendFailedRetry': 'Sending failed. Your question is still here - press Send to try again.',
  'chat.useTranscript': 'Send this question',
  'chat.speakReply': 'Play answer',
  'chat.stopSpeaking': 'Stop',
  'chat.speaking': 'Playing\u2026',
  'chat.guestNote': 'You are chatting as a guest. Your conversation stays on this device.',
  'chat.assistantUnavailable': 'The assistant is unavailable right now. Please try again, or contact the shop directly.',
  'chat.voiceNotConfigured': 'Voice input is not configured on this server yet. Please type your question.',
  'chat.micDenied': 'Microphone access was blocked. Allow it in your browser settings, or type your question.',
  'chat.playbackFailed': 'Speech playback failed. The written answer is still above.',
  'chat.proposedItems': 'The assistant suggested these items. Review them in your cart.',
  'chat.addProposal': 'Add to cart',
  'chat.notOrderable': 'Not available to order',
  'chat.feedbackPrompt': 'Was this helpful?',
  'chat.feedbackThanks': 'Thank you for the feedback.',
  'chat.feedbackComment': 'Anything else to add? (optional)',

  'cart.title': 'Your cart',
  'cart.empty': 'Your cart is empty. Add products from the catalogue.',
  'cart.itemCount': '{count} items',
  'cart.subtotal': 'Subtotal',
  'cart.checkout': 'Review and confirm',
  'cart.clear': 'Clear cart',
  'cart.availabilityWarning': 'Some items cannot be ordered right now.',
  'cart.priceFromShop': 'Prices come from the shop and are confirmed by the server.',

  'checkout.title': 'Confirm your order',
  'checkout.fulfillment': 'How would you like to receive it?',
  'checkout.pickup': 'Pickup from the shop',
  'checkout.delivery': 'Home delivery',
  'checkout.name': 'Your name',
  'checkout.email': 'Email for order updates',
  'checkout.phone': 'Contact phone number',
  'checkout.phoneHint': 'The shop will call this number if needed.',
  'checkout.address': 'Delivery address',
  'checkout.addressHint': 'House, street, landmark and PIN code.',
  'checkout.notes': 'Note for the shop',
  'checkout.notesHint': 'For example: deliver after 6 pm.',
  'checkout.optInEmail': 'Email me when the order status changes',
  'checkout.confirm': 'Place order request',
  'checkout.confirming': 'Sending your order\u2026',
  'checkout.noPayment': 'No payment is taken in the app. You pay the shop directly.',
  'checkout.signInRequired': 'Sign in with Google to send this order. Your cart will be kept.',
  'checkout.success': 'Order request sent to {business}.',
  'checkout.successNote': 'The shop will confirm your order. You can follow the status in Orders.',
  'checkout.emailSent': 'A notification email was sent to the shop.',
  'checkout.emailSkipped': 'The shop has not enabled order emails, so no email was sent. The order is saved in the app.',
  'checkout.emailFailed': 'The order is saved, but the notification email could not be delivered.',
  'checkout.viewOrder': 'View order',
  'checkout.deliveryUnavailable': 'This shop does not offer delivery.',
  'checkout.pickupUnavailable': 'This shop does not offer pickup.',

  'orders.title': 'Your orders',
  'orders.orderCode': 'Order {code}',
  'orders.placedOn': 'Placed {date}',
  'orders.statusHistory': 'Status history',
  'orders.items': 'Items',
  'orders.contactShop': 'Contact the shop',
  'orders.reviewOrder': 'Rate this order',
  'orders.reviewSubmitted': 'Thank you. Your review is now visible to the shop.',
  'orders.reviewLocked': 'You can review this order once the shop marks it completed.',
  'orders.alreadyReviewed': 'You have already reviewed this order.',
  'orders.rating': 'Rating',
  'orders.comment': 'Comment',
  'orders.commentHint': 'Tell other customers what went well or what could improve.',
  'orders.tags': 'What stood out?',
  'orders.submitReview': 'Submit review',
  'orders.refreshHint': 'Status is loaded fresh each time you open this page.',

  'status.NEW': 'New',
  'status.ACCEPTED': 'Accepted',
  'status.PREPARING': 'Preparing',
  'status.READY_FOR_PICKUP': 'Ready for pickup',
  'status.OUT_FOR_DELIVERY': 'Out for delivery',
  'status.COMPLETED': 'Completed',
  'status.CANCELLED': 'Cancelled',

  'tag.PRODUCT_QUALITY': 'Product quality',
  'tag.COMMUNICATION': 'Communication/service',
  'tag.PACKAGING': 'Packaging',
  'tag.VALUE': 'Value for money',
  'tag.DELIVERY_PICKUP': 'Delivery/pickup',

  'account.title': 'Your account',
  'account.profile': 'Profile',
  'account.recentStores': 'Recently accessed shops',
  'account.recentNote': 'Saved to your account so they follow you across devices.',
  'account.emailUpdates': 'Order update emails',
  'account.emailUpdatesHint': 'We only email you about your own orders.',
  'account.phone': 'Phone number',
  'account.saved': 'Your details were saved.',
  'account.noOrders': 'No orders yet. Explore shops to get started.',

  'merchant.setupTitle': 'Tell us about your business',
  'merchant.setupIntro': 'You can change all of this later from the Business tab.',
  'merchant.businessName': 'Business name',
  'merchant.ownerName': 'Owner name',
  'merchant.primaryCategory': 'Primary category',
  'merchant.chooseCategory': 'Choose a category',
  'merchant.addressLine': 'Shop address',
  'merchant.addressHint': 'Street, building or a nearby landmark.',
  'merchant.city': 'City or town',
  'merchant.state': 'State',
  'merchant.pincode': 'PIN code',
  'merchant.publicPhone': 'Public phone number',
  'merchant.publicPhoneHint': 'Shown to customers. Keep your account email private.',
  'merchant.locationPin': 'Location pin',
  'merchant.locationPinHint': 'Optional. Add coordinates if you want to show your exact spot.',
  'merchant.useMyLocation': 'Use my current location',
  'merchant.locationCaptured': 'Location captured. You can still edit the numbers below.',
  'merchant.locationDenied': 'Location permission was blocked. Type the address instead - a pin is optional.',
  'merchant.locationUnsupported': 'This browser cannot share a location. Type the address instead - a pin is optional.',
  'merchant.latitude': 'Latitude',
  'merchant.longitude': 'Longitude',
  'merchant.createBusiness': 'Create my business',
  'merchant.noBusiness': 'No business linked to this account yet.',
  'merchant.createBusinessCta': 'Set up your business',
  'merchant.overview': 'Business overview',
  'merchant.needsAttention': 'Needs attention',
  'merchant.newOrders': 'New orders',
  'merchant.openConversations': 'Open customer questions',
  'merchant.nothingNeedsAttention': 'Nothing needs your attention right now.',
  'merchant.inProgress': 'Orders in progress',
  'merchant.completedOrders': 'Completed orders',
  'merchant.topProducts': 'Top products',
  'merchant.topProductsHint': 'Calculated from completed orders.',
  'merchant.topProductsEmpty': 'No completed orders yet, so there is nothing to rank.',
  'merchant.recentReviews': 'Recent ratings and comments',
  'merchant.avgRating': 'Average rating',
  'merchant.reviewSourceOrder': 'Order review',
  'merchant.reviewSourceConversation': 'Conversation feedback',
  'merchant.availabilityBreakdown': 'Catalogue availability',
  'merchant.recentOrders': 'Recent orders',

  'merchant.orders': 'Orders',
  'merchant.filterStatus': 'Filter by status',
  'merchant.updateStatus': 'Update status',
  'merchant.statusUpdated': 'Status updated to {status}.',
  'merchant.customerDetails': 'Customer and fulfilment',
  'merchant.customerName': 'Customer',
  'merchant.customerPhone': 'Phone',
  'merchant.customerEmail': 'Email',
  'merchant.fulfillment': 'Fulfilment',
  'merchant.deliveryAddress': 'Delivery address',
  'merchant.statusNote': 'Note for the status history (optional)',
  'merchant.nextStatuses': 'Available next steps',
  'merchant.noNextStatuses': 'This order is closed and cannot be changed further.',
  'merchant.emailSentCustomer': 'The customer was emailed about this change.',
  'merchant.emailSkippedCustomer': 'The customer has not opted in to order emails, so no email was sent.',

  'merchant.products': 'Products',
  'merchant.addProduct': 'Add product',
  'merchant.editProduct': 'Edit product',
  'merchant.productName': 'Product name',
  'merchant.productPrice': 'Price (₹)',
  'merchant.productAvailability': 'Availability',
  'merchant.productDescription': 'Description',
  'merchant.productCategory': 'Category',
  'merchant.productAliases': 'Alternate names',
  'merchant.productAliasesHint': 'Other names customers may use, separated by commas. Example: atta, aata.',
  'merchant.availabilityAvailable': 'Available',
  'merchant.availabilityOutOfStock': 'Out of stock',
  'merchant.availabilityUnknown': 'Unknown',
  'merchant.availabilityUnknownHint': 'Use Unknown when you have not checked the shelf. It is never shown as Available.',
  'merchant.importExport': 'Import and export',
  'merchant.importIntro': 'Download the template, fill it in and upload it. You can edit availability in the app afterwards.',
  'merchant.downloadTemplate': 'Download XLSX template',
  'merchant.downloadTemplateCsv': 'Download CSV template',
  'merchant.exportProducts': 'Export current catalogue',
  'merchant.exportCsv': 'Export as CSV',
  'merchant.chooseFile': 'Choose .xlsx or .csv file',
  'merchant.preview': 'Check before saving',
  'merchant.previewIntro': 'Nothing is saved until you confirm.',
  'merchant.rowsValid': '{count} rows ready',
  'merchant.rowsInvalid': '{count} rows have errors',
  'merchant.rowErrors': 'Errors to fix',
  'merchant.rowWarnings': 'Warnings',
  'merchant.rowPreview': 'Row preview',
  'merchant.rowPreviewHint': 'Untick anything you do not want to save. Only ticked rows are imported.',
  'merchant.includeRow': 'Include',
  'merchant.importSavedSkipped': 'Saved: {created} added, {updated} updated, {skipped} skipped.',
  'merchant.confirmImport': 'Save {count} products',
  'merchant.importSaved': 'Saved: {created} added, {updated} updated.',
  'merchant.importNothingSaved': 'Nothing was saved because the file still has errors.',
  'merchant.importEmpty': 'The file has no product rows.',
  'merchant.archived': 'Archived',
  'merchant.showArchived': 'Show archived',
  'merchant.productArchived': 'Product archived. It is hidden from customers.',
  'merchant.productRestored': 'Product restored.',

  'merchant.businessProfile': 'Business profile',
  'merchant.publicDetails': 'Public details',
  'merchant.storeHours': 'Store hours',
  'merchant.day': 'Day',
  'merchant.closed': 'Closed',
  'merchant.opens': 'Opens',
  'merchant.closes': 'Closes',
  'merchant.copyMonday': 'Copy Monday to all days',
  'merchant.storeInfo': 'Store information for the assistant',
  'merchant.assistantNotes': 'Extra information for the assistant',
  'merchant.assistantNotesHint': 'For example: we restock vegetables every morning. Keep it factual.',
  'merchant.deliveryNotes': 'Delivery details',
  'merchant.paymentMethods': 'Accepted payment methods',
  'merchant.paymentMethodsHint': 'One per line. Shown as information only; no payments are processed.',
  'merchant.returnPolicy': 'Return policy',
  'merchant.faqs': 'Frequently asked questions',
  'merchant.addFaq': 'Add a question',
  'merchant.faqQuestion': 'Question',
  'merchant.faqAnswer': 'Answer',
  'merchant.notifications': 'Email notifications',
  'merchant.notifyNewOrders': 'Email me when a new order arrives',
  'merchant.notifyEmail': 'Notification email address',
  'merchant.notifyEmailHint': 'Different from your login email if you prefer.',
  'merchant.visibility': 'Visibility',
  'merchant.isActive': 'Business is active',
  'merchant.isPublic': 'Show in the customer directory',
  'merchant.saved': 'Your changes were saved.',
  'merchant.noEmailConfigured': 'Email delivery is not configured on this server, so notifications cannot be sent yet.',

  'merchant.conversations': 'Customer questions',
  'merchant.markResolved': 'Mark resolved',
  'merchant.markOpen': 'Reopen',
  'merchant.guestCustomer': 'Guest customer',
  'merchant.conversationFeedback': 'Conversation feedback',

  'error.network': 'We could not reach the server. Check your connection and try again.',
  'error.notFound': 'We could not find that page.',
  'error.forbidden': 'You do not have access to that.',
  'error.validation': 'Please check the highlighted fields.',
} as const;

export type StringKey = keyof typeof en;

type Table = Partial<Record<StringKey, string>>;

const bn: Table = {
  'app.tagline': 'আপনার দোকান, সব ভাষায়।',
  'app.languageLabel': 'ভাষা',
  'app.chooseLanguage': 'আপনার ভাষা বেছে নিন',
  'app.skipToContent': 'মূল বিষয়বস্তুতে যান',

  'nav.explore': 'দোকান খুঁজুন',
  'nav.exploreAsCustomer': 'ক্রেতা হিসেবে দেখুন',
  'nav.manageBusiness': 'ব্যবসা সামলান বা শুরু করুন',
  'nav.orders': 'অর্ডার',
  'nav.account': 'অ্যাকাউন্ট',
  'nav.overview': 'সারসংক্ষেপ',
  'nav.products': 'পণ্য',
  'nav.business': 'ব্যবসা',
  'nav.conversations': 'কথোপকথন',
  'nav.reviews': 'পর্যালোচনা',
  'nav.signOut': 'সাইন আউট',
  'nav.signIn': 'সাইন ইন',
  'nav.menu': 'মেনু',

  'landing.explore': 'ক্রেতা হিসেবে দেখুন',
  'landing.setUpBusiness': 'আমার ব্যবসা শুরু করুন',
  'landing.customerNote': 'অ্যাকাউন্ট ছাড়াই দোকান দেখুন ও প্রশ্ন করুন।',
  'landing.businessNote': 'দোকান, পণ্য ও অর্ডার সামলাতে অ্যাকাউন্ট তৈরি করুন।',
  'landing.howItWorks': 'DukaanSaathi কীভাবে কাজ করে',
  'landing.step1Title': 'কাছের দোকান খুঁজুন',
  'landing.step1Body': 'নাম, ধরন বা এলাকা দিয়ে স্থানীয় দোকান খুঁজুন।',
  'landing.step2Title': 'নিজের ভাষায় জিজ্ঞাসা করুন',
  'landing.step2Body': 'ইংরেজি, বাংলা বা হিন্দিতে লিখুন বা বলুন, দোকানের নিজের তথ্য থেকেই উত্তর পাবেন।',
  'landing.step3Title': 'অর্ডার করুন',
  'landing.step3Body': 'কার্ট সাজিয়ে মোট দেখে নিশ্চিত করুন। অর্ডার পাঠাতে Google দিয়ে সাইন ইন করুন।',
  'landing.forBusinesses': 'ব্যবসার মালিকদের জন্য',
  'landing.businessPoint1': 'স্প্রেডশিট থেকে পণ্যের তালিকা প্রকাশ করুন',
  'landing.businessPoint2': 'তিন ভাষায় ক্রেতার প্রশ্নের স্বয়ংক্রিয় উত্তর',
  'landing.businessPoint3': 'অর্ডার দেখুন ও অবস্থা পরিবর্তন করুন',

  'auth.customerSignIn': 'ক্রেতা সাইন ইন',
  'auth.customerSignInIntro': 'অর্ডার দিতে ও অর্ডারের ইতিহাস দেখতে Google দিয়ে সাইন ইন করুন।',
  'auth.continueWithGoogle': 'Google দিয়ে চালিয়ে যান',
  'auth.businessLogin': 'ব্যবসার লগইন',
  'auth.businessLoginIntro': 'দোকান, পণ্য ও অর্ডার সামলাতে সাইন ইন করুন।',
  'auth.createBusinessAccount': 'ব্যবসার অ্যাকাউন্ট তৈরি করুন',
  'auth.businessSignUpIntro': 'আপনার দোকানের জন্য অ্যাকাউন্ট তৈরি করুন। পরের ধাপে দোকানের তথ্য দেবেন।',
  'auth.email': 'ইমেল ঠিকানা',
  'auth.password': 'পাসওয়ার্ড',
  'auth.confirmPassword': 'পাসওয়ার্ড নিশ্চিত করুন',
  'auth.ownerName': 'আপনার নাম',
  'auth.newBusinessOwner': 'নতুন ব্যবসার মালিক?',
  'auth.existingBusinessOwner': 'আগেই ব্যবসার অ্যাকাউন্ট আছে?',
  'auth.customerBrowsing': 'শুধু দেখতে চান?',
  'auth.goToExplore': 'অ্যাকাউন্ট ছাড়াই দোকান দেখুন',
  'auth.checkEmail': 'অ্যাকাউন্ট নিশ্চিত করতে ইমেল দেখুন, তারপর লগইন করুন।',
  'auth.signedInAs': '{email} হিসেবে সাইন ইন করা আছে',
  'auth.passwordMismatch': 'দুটি পাসওয়ার্ড মিলছে না।',
  'auth.passwordTooShort': 'কমপক্ষে ৮টি অক্ষর ব্যবহার করুন।',
  'auth.whyGoogle': 'অর্ডারের জন্য যাচাই করা অ্যাকাউন্ট দরকার, যাতে দোকান আপনার সাথে যোগাযোগ করতে পারে। দেখা ও চ্যাট সবার জন্য খোলা।',

  'common.loading': 'লোড হচ্ছে\u2026',
  'common.saving': 'সেভ হচ্ছে\u2026',
  'common.save': 'সেভ করুন',
  'common.cancel': 'বাতিল',
  'common.close': 'বন্ধ করুন',
  'common.edit': 'সম্পাদনা',
  'common.delete': 'মুছুন',
  'common.archive': 'আর্কাইভ করুন',
  'common.restore': 'ফিরিয়ে আনুন',
  'common.back': 'পিছনে',
  'common.retry': 'আবার চেষ্টা করুন',
  'common.search': 'খুঁজুন',
  'common.filter': 'ফিল্টার',
  'common.all': 'সব',
  'common.optional': 'ঐচ্ছিক',
  'common.required': 'আবশ্যক',
  'common.yes': 'হ্যাঁ',
  'common.no': 'না',
  'common.confirm': 'নিশ্চিত করুন',
  'common.add': 'যোগ করুন',
  'common.remove': 'সরান',
  'common.download': 'ডাউনলোড',
  'common.upload': 'আপলোড',
  'common.refresh': 'রিফ্রেশ',
  'common.notSet': 'দেওয়া হয়নি',
  'common.unknown': 'জানা নেই',
  'common.today': 'আজ',
  'common.resolved': 'সমাধান হয়েছে',
  'common.open': 'খোলা',
  'common.viewAll': 'সব দেখুন',
  'common.status': 'অবস্থা',
  'common.total': 'মোট',
  'common.quantity': 'পরিমাণ',
  'common.price': 'দাম',
  'common.name': 'নাম',
  'common.category': 'বিভাগ',
  'common.notes': 'নোট',
  'common.somethingWentWrong': 'কিছু ভুল হয়েছে।',
  'common.row': 'সারি {row}',

  'state.loading': 'লোড হচ্ছে\u2026',
  'state.emptyTitle': 'এখনও কিছু নেই',
  'state.emptyBusinesses': 'আপনার খোঁজে কোনো দোকান মেলেনি। অন্য শব্দ বা বিভাগ চেষ্টা করুন।',
  'state.emptyProducts': 'এই দোকান এখনও কোনো পণ্য প্রকাশ করেনি।',
  'state.emptyOrders': 'আপনি এখনও কোনো অর্ডার দেননি।',
  'state.emptyMerchantOrders': 'এখনও অর্ডার নেই। নতুন অর্ডার এখানে দেখা যাবে।',
  'state.emptyConversations': 'এখনও ক্রেতার প্রশ্ন নেই।',
  'state.emptyReviews': 'এখনও কোনো পর্যালোচনা নেই। অর্ডার সম্পূর্ণ হলে পর্যালোচনা আসবে।',
  'state.errorTitle': 'এটা লোড করা গেল না',
  'state.offline': 'সার্ভারে পৌঁছানো যাচ্ছে না। সংযোগ দেখে আবার চেষ্টা করুন।',

  'explore.title': 'কাছের দোকান খুঁজুন',
  'explore.searchLabel': 'দোকান খুঁজুন',
  'explore.searchPlaceholder': 'দোকানের নাম, এলাকা বা বিভাগ',
  'explore.categoryLabel': 'বিভাগ',
  'explore.allShops': 'সব দোকান',
  'explore.recentlyAccessed': 'সম্প্রতি দেখা',
  'explore.resultCount': '{count}টি দোকান',
  'explore.openNow': 'এখন খোলা',
  'explore.closedNow': 'বন্ধ',
  'explore.hoursUnknown': 'সময় দেওয়া হয়নি',
  'explore.products': '{count}টি পণ্য',

  'business.about': 'পরিচিতি',
  'business.hours': 'খোলার সময়',
  'business.contact': 'যোগাযোগ',
  'business.address': 'ঠিকানা',
  'business.options': 'পিকআপ ও ডেলিভারি',
  'business.pickup': 'পিকআপ আছে',
  'business.delivery': 'ডেলিভারি আছে',
  'business.noPickup': 'পিকআপ নেই',
  'business.noDelivery': 'ডেলিভারি নেই',
  'business.paymentMethods': 'গ্রহণযোগ্য পেমেন্ট',
  'business.paymentNote': 'শুধু তথ্যের জন্য। DukaanSaathi পেমেন্ট প্রসেস করে না।',
  'business.returnPolicy': 'ফেরতের নিয়ম',
  'business.faqs': 'সাধারণ প্রশ্ন',
  'business.catalog': 'পণ্য',
  'business.catalogSearch': 'পণ্য খুঁজুন',
  'business.quickNav': 'সরাসরি যান',
  'business.storeInformation': 'দোকানের তথ্য',
  'business.askShop': 'এই দোকানকে জিজ্ঞাসা করুন',
  'business.reviews': 'সাম্প্রতিক রেটিং',
  'business.ratingSummary': '{count}টি পর্যালোচনায় ৫-এর মধ্যে {rating}',
  'business.noRating': 'এখনও রেটিং নেই',
  'business.closedToday': 'বন্ধ',

  'product.available': 'উপলব্ধ',
  'product.outOfStock': 'স্টক নেই',
  'product.unknownAvailability': 'স্টক জানা নেই',
  'product.addToCart': 'যোগ করুন',
  'product.added': 'যোগ হয়েছে',
  'product.priceUnavailable': 'দাম জানতে দোকানে জিজ্ঞাসা করুন',

  'chat.title': '{business}-কে জিজ্ঞাসা করুন',
  'chat.intro': 'পণ্য, দাম, সময় বা নিয়ম নিয়ে জিজ্ঞাসা করুন। উত্তর আসবে এই দোকানের দেওয়া তথ্য থেকেই।',
  'chat.placeholder': 'আপনার প্রশ্ন লিখুন\u2026',
  'chat.send': 'পাঠান',
  'chat.recording': 'রেকর্ড হচ্ছে\u2026 শেষ হলে থামুন',
  'chat.startRecording': 'কণ্ঠে প্রশ্ন করুন',
  'chat.stopRecording': 'রেকর্ডিং বন্ধ করুন',
  'chat.transcribing': 'আপনার রেকর্ডিং লেখা হচ্ছে\u2026',
  'chat.transcriptReview': 'পাঠানোর আগে লেখাটি দেখে নিন। বদলাতেও পারেন।',
  'chat.detectedLanguage': 'শনাক্ত করা ভাষা: {language}',
  'chat.detectionUnclear': 'বলা ভাষা শনাক্ত করা যায়নি। নিচে বেছে নিন যাতে সঠিক কণ্ঠে উত্তর আসে।',
  'chat.spokenLanguage': 'আপনি যে ভাষায় বলেছেন',
  'chat.useInterfaceLanguage': 'ইন্টারফেসের ভাষার মতোই',
  'chat.chooseLanguage': 'আপনি যে ভাষায় বলেছেন সেটি বেছে নিন',
  'chat.pickLanguageBeforeSending': 'পাঠানোর আগে বলা ভাষাটি বেছে নিন, যাতে উত্তর ও কণ্ঠ ঠিক হয়।',
  'chat.replyLanguage': 'উত্তরের ভাষা',
  'chat.detectedFromScript': 'লিপি থেকে শনাক্ত: {language}',
  'chat.followInterfaceLanguage': 'ইন্টারফেসের ভাষা অনুসরণ করুন',
  'chat.waitingForReply': 'দোকানের সহকারীর উত্তর আসছে\u2026',
  'chat.sendFailedRetry': 'পাঠানো যায়নি। আপনার প্রশ্ন এখানেই আছে - আবার পাঠান।',
  'chat.useTranscript': 'এই প্রশ্ন পাঠান',
  'chat.speakReply': 'উত্তর শুনুন',
  'chat.stopSpeaking': 'থামুন',
  'chat.speaking': 'চলছে\u2026',
  'chat.guestNote': 'আপনি অতিথি হিসেবে কথা বলছেন। কথোপকথন এই ডিভাইসেই থাকবে।',
  'chat.assistantUnavailable': 'সহকারী এখন উপলব্ধ নয়। আবার চেষ্টা করুন বা সরাসরি দোকানে যোগাযোগ করুন।',
  'chat.voiceNotConfigured': 'এই সার্ভারে কণ্ঠ ইনপুট এখনো চালু হয়নি। অনুগ্রহ করে প্রশ্ন লিখুন।',
  'chat.micDenied': 'মাইক্রোফোন ব্যবহারের অনুমতি দেওয়া হয়নি। ব্রাউজার সেটিংয়ে অনুমতি দিন, বা প্রশ্ন লিখুন।',
  'chat.playbackFailed': 'কণ্ঠে শোনানো গেল না। লেখা উত্তর উপরে আছে।',
  'chat.proposedItems': 'সহকারী এই পণ্যগুলি সাজিয়েছে। কার্টে দেখে নিন।',
  'chat.addProposal': 'কার্টে যোগ করুন',
  'chat.notOrderable': 'অর্ডার করা যাবে না',
  'chat.feedbackPrompt': 'এটি কি সহায়ক ছিল?',
  'chat.feedbackThanks': 'মতামতের জন্য ধন্যবাদ।',
  'chat.feedbackComment': 'আর কিছু বলতে চান? (ঐচ্ছিক)',

  'cart.title': 'আপনার কার্ট',
  'cart.empty': 'কার্ট খালি। তালিকা থেকে পণ্য যোগ করুন।',
  'cart.itemCount': '{count}টি পণ্য',
  'cart.subtotal': 'উপমোট',
  'cart.checkout': 'দেখে নিশ্চিত করুন',
  'cart.clear': 'কার্ট খালি করুন',
  'cart.availabilityWarning': 'কিছু পণ্য এখন অর্ডার করা যাবে না।',
  'cart.priceFromShop': 'দাম আসে দোকান থেকে এবং সার্ভার তা যাচাই করে।',

  'checkout.title': 'অর্ডার নিশ্চিত করুন',
  'checkout.fulfillment': 'কীভাবে পেতে চান?',
  'checkout.pickup': 'দোকান থেকে নেব',
  'checkout.delivery': 'বাড়িতে ডেলিভারি',
  'checkout.name': 'আপনার নাম',
  'checkout.email': 'অর্ডার আপডেটের ইমেল',
  'checkout.phone': 'যোগাযোগের ফোন নম্বর',
  'checkout.phoneHint': 'দরকার হলে দোকান এই নম্বরে ফোন করবে।',
  'checkout.address': 'ডেলিভারির ঠিকানা',
  'checkout.addressHint': 'বাড়ি, রাস্তা, ল্যান্ডমার্ক ও পিন কোড।',
  'checkout.notes': 'দোকানের জন্য নোট',
  'checkout.notesHint': 'যেমন: সন্ধ্যা ৬টার পরে দেবেন।',
  'checkout.optInEmail': 'অর্ডারের অবস্থা বদলালে ইমেল করুন',
  'checkout.confirm': 'অর্ডারের অনুরোধ পাঠান',
  'checkout.confirming': 'আপনার অর্ডার পাঠানো হচ্ছে\u2026',
  'checkout.noPayment': 'অ্যাপে কোনো পেমেন্ট নেওয়া হয় না। আপনি সরাসরি দোকানে দেবেন।',
  'checkout.signInRequired': 'এই অর্ডার পাঠাতে Google দিয়ে সাইন ইন করুন। কার্ট রক্ষা করা হবে।',
  'checkout.success': '{business}-কে অর্ডারের অনুরোধ পাঠানো হয়েছে।',
  'checkout.successNote': 'দোকান আপনার অর্ডার নিশ্চিত করবে। অর্ডার পাতায় অবস্থা দেখতে পাবেন।',
  'checkout.emailSent': 'দোকানে নোটিফিকেশন ইমেল পাঠানো হয়েছে।',
  'checkout.emailSkipped': 'দোকান অর্ডার ইমেল চালু করেনি, তাই কোনো ইমেল যায়নি। অর্ডার অ্যাপে সেভ আছে।',
  'checkout.emailFailed': 'অর্ডার সেভ হয়েছে, কিন্তু নোটিফিকেশন ইমেল পাঠানো যায়নি।',
  'checkout.viewOrder': 'অর্ডার দেখুন',

  'orders.title': 'আপনার অর্ডার',
  'orders.orderCode': 'অর্ডার {code}',
  'orders.placedOn': '{date}-এ দেওয়া',
  'orders.statusHistory': 'অবস্থার ইতিহাস',
  'orders.items': 'পণ্য',
  'orders.contactShop': 'দোকানে যোগাযোগ করুন',
  'orders.reviewOrder': 'এই অর্ডারের রেটিং দিন',
  'orders.reviewSubmitted': 'ধন্যবাদ। আপনার পর্যালোচনা দোকান দেখতে পাবে।',
  'orders.reviewLocked': 'দোকান অর্ডারটি সম্পূর্ণ করলে আপনি পর্যালোচনা দিতে পারবেন।',
  'orders.alreadyReviewed': 'আপনি ইতিমধ্যেই এই অর্ডারের পর্যালোচনা দিয়েছেন।',
  'orders.rating': 'রেটিং',
  'orders.comment': 'মন্তব্য',
  'orders.tags': 'কী ভালো লেগেছে?',
  'orders.submitReview': 'পর্যালোচনা পাঠান',
  'orders.refreshHint': 'প্রতিবার এই পাতা খুললে অবস্থা নতুন করে লোড হয়।',

  'status.NEW': 'নতুন',
  'status.ACCEPTED': 'গৃহীত',
  'status.PREPARING': 'প্রস্তুত হচ্ছে',
  'status.READY_FOR_PICKUP': 'পিকআপের জন্য তৈরি',
  'status.OUT_FOR_DELIVERY': 'ডেলিভারির পথে',
  'status.COMPLETED': 'সম্পূর্ণ',
  'status.CANCELLED': 'বাতিল',

  'tag.PRODUCT_QUALITY': 'পণ্যের গুণমান',
  'tag.COMMUNICATION': 'যোগাযোগ/পরিষেবা',
  'tag.PACKAGING': 'প্যাকিং',
  'tag.VALUE': 'দামের তুলনায় মান',
  'tag.DELIVERY_PICKUP': 'ডেলিভারি/পিকআপ',

  'account.title': 'আপনার অ্যাকাউন্ট',
  'account.profile': 'প্রোফাইল',
  'account.recentStores': 'সম্প্রতি দেখা দোকান',
  'account.recentNote': 'আপনার অ্যাকাউন্টে সেভ হয়, তাই সব ডিভাইসে পাওয়া যায়।',
  'account.emailUpdates': 'অর্ডার আপডেটের ইমেল',
  'account.emailUpdatesHint': 'শুধু আপনার নিজের অর্ডার নিয়েই ইমেল করি।',
  'account.phone': 'ফোন নম্বর',
  'account.saved': 'আপনার তথ্য সেভ হয়েছে।',
  'account.noOrders': 'এখনও অর্ডার নেই। শুরু করতে দোকান দেখুন।',

  'merchant.setupTitle': 'আপনার ব্যবসার তথ্য দিন',
  'merchant.setupIntro': 'এগুলো পরে ব্যবসা ট্যাব থেকে বদলাতে পারবেন।',
  'merchant.businessName': 'ব্যবসার নাম',
  'merchant.ownerName': 'মালিকের নাম',
  'merchant.primaryCategory': 'মূল বিভাগ',
  'merchant.chooseCategory': 'একটি বিভাগ বাছুন',
  'merchant.addressLine': 'দোকানের ঠিকানা',
  'merchant.addressHint': 'রাস্তা, বাড়ি বা কাছের ল্যান্ডমার্ক।',
  'merchant.city': 'শহর বা গ্রাম',
  'merchant.state': 'রাজ্য',
  'merchant.pincode': 'পিন কোড',
  'merchant.publicPhone': 'প্রকাশ্য ফোন নম্বর',
  'merchant.publicPhoneHint': 'ক্রেতারা দেখতে পাবে। অ্যাকাউন্টের ইমেল গোপন রাখুন।',
  'merchant.locationPin': 'লোকেশন পিন',
  'merchant.locationPinHint': 'ঐচ্ছিক। সঠিক জায়গা দেখাতে চাইলে কোঅর্ডিনেট দিন।',
  'merchant.useMyLocation': 'আমার বর্তমান অবস্থান নিন',
  'merchant.locationCaptured': 'অবস্থান নেওয়া হয়েছে। নিচের সংখ্যা বদলাতেও পারেন।',
  'merchant.locationDenied': 'অবস্থানের অনুমতি দেওয়া হয়নি। ঠিকানা লিখুন - পিন ঐচ্ছিক।',
  'merchant.locationUnsupported': 'এই ব্রাউজার অবস্থান দিতে পারে না। ঠিকানা লিখুন - পিন ঐচ্ছিক।',
  'merchant.latitude': 'অক্ষাংশ',
  'merchant.longitude': 'দ্রাঘিমাংশ',
  'merchant.createBusiness': 'আমার ব্যবসা তৈরি করুন',
  'merchant.noBusiness': 'এই অ্যাকাউন্টের সাথে এখনও কোনো ব্যবসা যুক্ত নেই।',
  'merchant.createBusinessCta': 'ব্যবসা শুরু করুন',
  'merchant.overview': 'ব্যবসার সারসংক্ষেপ',
  'merchant.needsAttention': 'মনোযোগ দরকার',
  'merchant.newOrders': 'নতুন অর্ডার',
  'merchant.openConversations': 'খোলা ক্রেতার প্রশ্ন',
  'merchant.nothingNeedsAttention': 'এই মুহূর্তে কিছুই মনোযোগ দরকার নেই।',
  'merchant.inProgress': 'চলমান অর্ডার',
  'merchant.completedOrders': 'সম্পূর্ণ অর্ডার',
  'merchant.topProducts': 'জনপ্রিয় পণ্য',
  'merchant.topProductsHint': 'সম্পূর্ণ অর্ডার থেকে হিসাব করা।',
  'merchant.topProductsEmpty': 'এখনও সম্পূর্ণ অর্ডার নেই, তাই তালিকা নেই।',
  'merchant.recentReviews': 'সাম্প্রতিক রেটিং ও মন্তব্য',
  'merchant.avgRating': 'গড় রেটিং',
  'merchant.reviewSourceOrder': 'অর্ডারের পর্যালোচনা',
  'merchant.reviewSourceConversation': 'কথোপকথনের মতামত',
  'merchant.availabilityBreakdown': 'তালিকার স্টক অবস্থা',
  'merchant.recentOrders': 'সাম্প্রতিক অর্ডার',

  'merchant.orders': 'অর্ডার',
  'merchant.filterStatus': 'অবস্থা দিয়ে ফিল্টার',
  'merchant.updateStatus': 'অবস্থা বদলান',
  'merchant.statusUpdated': 'অবস্থা বদলে {status} হয়েছে।',
  'merchant.customerDetails': 'ক্রেতা ও সরবরাহ',
  'merchant.customerName': 'ক্রেতা',
  'merchant.customerPhone': 'ফোন',
  'merchant.customerEmail': 'ইমেল',
  'merchant.fulfillment': 'সরবরাহের ধরন',
  'merchant.deliveryAddress': 'ডেলিভারির ঠিকানা',
  'merchant.statusNote': 'ইতিহাসের জন্য নোট (ঐচ্ছিক)',
  'merchant.nextStatuses': 'পরের সম্ভাব্য ধাপ',
  'merchant.noNextStatuses': 'এই অর্ডার বন্ধ, আর বদলানো যাবে না।',
  'merchant.emailSentCustomer': 'এই পরিবর্তনের ইমেল ক্রেতাকে পাঠানো হয়েছে।',
  'merchant.emailSkippedCustomer': 'ক্রেতা অর্ডার ইমেল চালু করেননি, তাই ইমেল যায়নি।',

  'merchant.products': 'পণ্য',
  'merchant.addProduct': 'পণ্য যোগ করুন',
  'merchant.editProduct': 'পণ্য সম্পাদনা',
  'merchant.productName': 'পণ্যের নাম',
  'merchant.productPrice': 'দাম (₹)',
  'merchant.productAvailability': 'স্টক অবস্থা',
  'merchant.productDescription': 'বিবরণ',
  'merchant.productCategory': 'বিভাগ',
  'merchant.productAliases': 'বিকল্প নাম',
  'merchant.productAliasesHint': 'ক্রেতারা যে অন্য নামে খোঁজে, কমা দিয়ে লিখুন। যেমন: atta, aata।',
  'merchant.availabilityAvailable': 'উপলব্ধ',
  'merchant.availabilityOutOfStock': 'স্টক নেই',
  'merchant.availabilityUnknown': 'জানা নেই',
  'merchant.availabilityUnknownHint': 'দেখে যাচাই না করলে "জানা নেই" দিন। এটি কখনও "উপলব্ধ" হিসেবে দেখানো হয় না।',
  'merchant.importExport': 'আমদানি ও রপ্তানি',
  'merchant.importIntro': 'টেমপ্লেট নামিয়ে ভরুন, তারপর আপলোড করুন। পরে অ্যাপ থেকেই স্টক বদলাতে পারবেন।',
  'merchant.downloadTemplate': 'XLSX টেমপ্লেট নামান',
  'merchant.downloadTemplateCsv': 'CSV টেমপ্লেট নামান',
  'merchant.exportProducts': 'বর্তমান তালিকা রপ্তানি',
  'merchant.exportCsv': 'CSV হিসেবে রপ্তানি',
  'merchant.chooseFile': '.xlsx বা .csv ফাইল বাছুন',
  'merchant.preview': 'সেভ করার আগে দেখে নিন',
  'merchant.previewIntro': 'আপনি নিশ্চিত না করলে কিছুই সেভ হয় না।',
  'merchant.rowsValid': '{count}টি সারি প্রস্তুত',
  'merchant.rowsInvalid': '{count}টি সারিতে ভুল আছে',
  'merchant.rowErrors': 'যে ভুলগুলো ঠিক করতে হবে',
  'merchant.rowWarnings': 'সতর্কতা',
  'merchant.rowPreview': 'সারির পূর্বরূপ',
  'merchant.rowPreviewHint': 'যা সেভ করতে চান না তা টিক তুলে দিন। শুধু টিক দেওয়া সারি সেভ হবে।',
  'merchant.includeRow': 'সেভ করুন',
  'merchant.importSavedSkipped': 'সেভ হয়েছে: {created}টি যোগ, {updated}টি হালনাগাদ, {skipped}টি বাদ।',
  'merchant.confirmImport': '{count}টি পণ্য সেভ করুন',
  'merchant.importSaved': 'সেভ হয়েছে: {created}টি যোগ, {updated}টি হালনাগাদ।',
  'merchant.importNothingSaved': 'ফাইলে ভুল থাকায় কিছুই সেভ হয়নি।',
  'merchant.importEmpty': 'ফাইলে কোনো পণ্যের সারি নেই।',
  'merchant.archived': 'আর্কাইভ করা',
  'merchant.showArchived': 'আর্কাইভ দেখান',
  'merchant.productArchived': 'পণ্য আর্কাইভ করা হয়েছে। ক্রেতারা আর দেখবে না।',
  'merchant.productRestored': 'পণ্য ফিরিয়ে আনা হয়েছে।',

  'merchant.businessProfile': 'ব্যবসার প্রোফাইল',
  'merchant.publicDetails': 'প্রকাশ্য তথ্য',
  'merchant.storeHours': 'দোকানের সময়',
  'merchant.day': 'দিন',
  'merchant.closed': 'বন্ধ',
  'merchant.opens': 'খোলে',
  'merchant.closes': 'বন্ধ হয়',
  'merchant.copyMonday': 'সোমবারের সময় সব দিনে বসান',
  'merchant.storeInfo': 'সহকারীর জন্য দোকানের তথ্য',
  'merchant.assistantNotes': 'সহকারীর জন্য অতিরিক্ত তথ্য',
  'merchant.assistantNotesHint': 'যেমন: প্রতি সকালে সবজি আসে। তথ্য সত্যি রাখুন।',
  'merchant.deliveryNotes': 'ডেলিভারির বিবরণ',
  'merchant.paymentMethods': 'গ্রহণযোগ্য পেমেন্ট',
  'merchant.paymentMethodsHint': 'প্রতি লাইনে একটি। শুধু তথ্যের জন্য; পেমেন্ট প্রসেস হয় না।',
  'merchant.returnPolicy': 'ফেরতের নিয়ম',
  'merchant.faqs': 'প্রায়শই জিজ্ঞাসিত প্রশ্ন',
  'merchant.addFaq': 'প্রশ্ন যোগ করুন',
  'merchant.faqQuestion': 'প্রশ্ন',
  'merchant.faqAnswer': 'উত্তর',
  'merchant.notifications': 'ইমেল নোটিফিকেশন',
  'merchant.notifyNewOrders': 'নতুন অর্ডার এলে ইমেল করুন',
  'merchant.notifyEmail': 'নোটিফিকেশনের ইমেল',
  'merchant.notifyEmailHint': 'চাইলে লগইন ইমেলের থেকে আলাদা দিতে পারেন।',
  'merchant.visibility': 'দৃশ্যমানতা',
  'merchant.isActive': 'ব্যবসা সক্রিয়',
  'merchant.isPublic': 'ক্রেতার তালিকায় দেখান',
  'merchant.saved': 'আপনার পরিবর্তন সেভ হয়েছে।',
  'merchant.noEmailConfigured': 'এই সার্ভারে ইমেল পাঠানো চালু নেই, তাই নোটিফিকেশন পাঠানো যাবে না।',

  'merchant.conversations': 'ক্রেতার প্রশ্ন',
  'merchant.markResolved': 'সমাধান হয়েছে চিহ্নিত করুন',
  'merchant.markOpen': 'আবার খুলুন',
  'merchant.guestCustomer': 'অতিথি ক্রেতা',
  'merchant.conversationFeedback': 'কথোপকথনের মতামত',

  'error.network': 'সার্ভারে পৌঁছানো যাচ্ছে না। সংযোগ দেখে আবার চেষ্টা করুন।',
  'error.notFound': 'এই পাতাটি পাওয়া গেল না।',
  'error.forbidden': 'এতে আপনার অনুমতি নেই।',
  'error.validation': 'চিহ্নিত ঘরগুলো দেখে নিন।',
};

const hi: Table = {
  'app.tagline': 'आपकी दुकान, हर भाषा में।',
  'app.languageLabel': 'भाषा',
  'app.chooseLanguage': 'अपनी भाषा चुनें',
  'app.skipToContent': 'मुख्य सामग्री पर जाएँ',

  'nav.explore': 'दुकानें देखें',
  'nav.exploreAsCustomer': 'ग्राहक के रूप में देखें',
  'nav.manageBusiness': 'व्यवसाय संभालें या शुरू करें',
  'nav.orders': 'ऑर्डर',
  'nav.account': 'खाता',
  'nav.overview': 'सारांश',
  'nav.products': 'उत्पाद',
  'nav.business': 'व्यवसाय',
  'nav.conversations': 'बातचीत',
  'nav.reviews': 'समीक्षाएँ',
  'nav.signOut': 'साइन आउट',
  'nav.signIn': 'साइन इन',
  'nav.menu': 'मेन्यू',

  'landing.explore': 'ग्राहक के रूप में देखें',
  'landing.setUpBusiness': 'मेरा व्यवसाय शुरू करें',
  'landing.customerNote': 'बिना खाता दुकानें देखें और सवाल पूछें।',
  'landing.businessNote': 'दुकान, उत्पाद और ऑर्डर संभालने के लिए खाता बनाएँ।',
  'landing.howItWorks': 'DukaanSaathi कैसे काम करता है',
  'landing.step1Title': 'पास की दुकान खोजें',
  'landing.step1Body': 'नाम, श्रेणी या इलाके से स्थानीय दुकानें खोजें।',
  'landing.step2Title': 'अपनी भाषा में पूछें',
  'landing.step2Body': 'अंग्रेज़ी, बांग्ला या हिंदी में लिखें या बोलें, जवाब दुकान की अपनी जानकारी से मिलेगा।',
  'landing.step3Title': 'ऑर्डर करें',
  'landing.step3Body': 'कार्ट बनाएँ, कुल देखें और पुष्टि करें। ऑर्डर भेजने के लिए Google से साइन इन करें।',
  'landing.forBusinesses': 'व्यवसाय मालिकों के लिए',
  'landing.businessPoint1': 'स्प्रेडशीट से अपनी सूची प्रकाशित करें',
  'landing.businessPoint2': 'तीन भाषाओं में ग्राहक के सवालों के स्वचालित जवाब',
  'landing.businessPoint3': 'ऑर्डर देखें और स्थिति बदलें',

  'auth.customerSignIn': 'ग्राहक साइन इन',
  'auth.customerSignInIntro': 'ऑर्डर देने और ऑर्डर इतिहास देखने के लिए Google से साइन इन करें।',
  'auth.continueWithGoogle': 'Google से जारी रखें',
  'auth.businessLogin': 'व्यवसाय लॉगिन',
  'auth.businessLoginIntro': 'दुकान, उत्पाद और ऑर्डर संभालने के लिए साइन इन करें।',
  'auth.createBusinessAccount': 'व्यवसाय खाता बनाएँ',
  'auth.businessSignUpIntro': 'अपनी दुकान के लिए खाता बनाएँ। अगले चरण में दुकान की जानकारी भरेंगे।',
  'auth.email': 'ईमेल पता',
  'auth.password': 'पासवर्ड',
  'auth.confirmPassword': 'पासवर्ड दोबारा',
  'auth.ownerName': 'आपका नाम',
  'auth.newBusinessOwner': 'नए व्यवसाय मालिक?',
  'auth.existingBusinessOwner': 'पहले से व्यवसाय खाता है?',
  'auth.customerBrowsing': 'सिर्फ़ देखना चाहते हैं?',
  'auth.goToExplore': 'बिना खाता दुकानें देखें',
  'auth.checkEmail': 'खाता पुष्ट करने के लिए ईमेल देखें, फिर लॉगिन करें।',
  'auth.signedInAs': '{email} के रूप में साइन इन',
  'auth.passwordMismatch': 'दोनों पासवर्ड मेल नहीं खाते।',
  'auth.passwordTooShort': 'कम से कम 8 अक्षर इस्तेमाल करें।',
  'auth.whyGoogle': 'ऑर्डर के लिए सत्यापित खाता चाहिए ताकि दुकान आपसे संपर्क कर सके। देखना और चैट सबके लिए खुला है।',

  'common.loading': 'लोड हो रहा है\u2026',
  'common.saving': 'सेव हो रहा है\u2026',
  'common.save': 'सेव करें',
  'common.cancel': 'रद्द करें',
  'common.close': 'बंद करें',
  'common.edit': 'संपादित करें',
  'common.delete': 'हटाएँ',
  'common.archive': 'संग्रह करें',
  'common.restore': 'वापस लाएँ',
  'common.back': 'वापस',
  'common.retry': 'फिर कोशिश करें',
  'common.search': 'खोजें',
  'common.filter': 'फ़िल्टर',
  'common.all': 'सभी',
  'common.optional': 'वैकल्पिक',
  'common.required': 'आवश्यक',
  'common.yes': 'हाँ',
  'common.no': 'नहीं',
  'common.confirm': 'पुष्टि करें',
  'common.add': 'जोड़ें',
  'common.remove': 'हटाएँ',
  'common.download': 'डाउनलोड',
  'common.upload': 'अपलोड',
  'common.refresh': 'रीफ़्रेश',
  'common.notSet': 'तय नहीं',
  'common.unknown': 'पता नहीं',
  'common.today': 'आज',
  'common.resolved': 'सुलझा',
  'common.open': 'खुला',
  'common.viewAll': 'सब देखें',
  'common.status': 'स्थिति',
  'common.total': 'कुल',
  'common.quantity': 'मात्रा',
  'common.price': 'कीमत',
  'common.name': 'नाम',
  'common.category': 'श्रेणी',
  'common.notes': 'टिप्पणी',
  'common.somethingWentWrong': 'कुछ गड़बड़ हुई।',
  'common.row': 'पंक्ति {row}',

  'state.loading': 'लोड हो रहा है\u2026',
  'state.emptyTitle': 'अभी कुछ नहीं है',
  'state.emptyBusinesses': 'आपकी खोज से कोई दुकान मेल नहीं खाई। दूसरा शब्द या श्रेणी आज़माएँ।',
  'state.emptyProducts': 'इस दुकान ने अभी कोई उत्पाद प्रकाशित नहीं किया।',
  'state.emptyOrders': 'आपने अभी कोई ऑर्डर नहीं दिया।',
  'state.emptyMerchantOrders': 'अभी कोई ऑर्डर नहीं। नए ऑर्डर यहाँ दिखेंगे।',
  'state.emptyConversations': 'अभी ग्राहक के सवाल नहीं हैं।',
  'state.emptyReviews': 'अभी कोई समीक्षा नहीं। ऑर्डर पूरा होने पर समीक्षा आती है।',
  'state.errorTitle': 'यह लोड नहीं हो सका',
  'state.offline': 'सर्वर तक नहीं पहुँच सके। कनेक्शन देखकर फिर कोशिश करें।',

  'explore.title': 'पास की दुकान खोजें',
  'explore.searchLabel': 'दुकान खोजें',
  'explore.searchPlaceholder': 'दुकान का नाम, इलाका या श्रेणी',
  'explore.categoryLabel': 'श्रेणी',
  'explore.allShops': 'सभी दुकानें',
  'explore.recentlyAccessed': 'हाल में देखी',
  'explore.resultCount': '{count} दुकानें',
  'explore.openNow': 'अभी खुला',
  'explore.closedNow': 'बंद',
  'explore.hoursUnknown': 'समय दर्ज नहीं',
  'explore.products': '{count} उत्पाद',

  'business.about': 'परिचय',
  'business.hours': 'खुलने का समय',
  'business.contact': 'संपर्क',
  'business.address': 'पता',
  'business.options': 'पिकअप और डिलीवरी',
  'business.pickup': 'पिकअप उपलब्ध',
  'business.delivery': 'डिलीवरी उपलब्ध',
  'business.noPickup': 'पिकअप नहीं',
  'business.noDelivery': 'डिलीवरी नहीं',
  'business.paymentMethods': 'स्वीकृत भुगतान',
  'business.paymentNote': 'केवल जानकारी के लिए। DukaanSaathi भुगतान प्रोसेस नहीं करता।',
  'business.returnPolicy': 'वापसी नीति',
  'business.faqs': 'आम सवाल',
  'business.catalog': 'उत्पाद',
  'business.catalogSearch': 'उत्पाद खोजें',
  'business.quickNav': 'सीधे जाएँ',
  'business.storeInformation': 'दुकान की जानकारी',
  'business.askShop': 'इस दुकान से पूछें',
  'business.reviews': 'हाल की रेटिंग',
  'business.ratingSummary': '{count} समीक्षाओं में 5 में से {rating}',
  'business.noRating': 'अभी रेटिंग नहीं',
  'business.closedToday': 'बंद',

  'product.available': 'उपलब्ध',
  'product.outOfStock': 'स्टॉक में नहीं',
  'product.unknownAvailability': 'स्टॉक पता नहीं',
  'product.addToCart': 'जोड़ें',
  'product.added': 'जुड़ गया',
  'product.priceUnavailable': 'कीमत के लिए दुकान से पूछें',

  'chat.title': '{business} से पूछें',
  'chat.intro': 'उत्पाद, कीमत, समय या नीति के बारे में पूछें। जवाब इसी दुकान की दी जानकारी से आते हैं।',
  'chat.placeholder': 'अपना सवाल लिखें\u2026',
  'chat.send': 'भेजें',
  'chat.recording': 'रिकॉर्ड हो रहा है\u2026 पूरा होने पर रोकें',
  'chat.startRecording': 'बोलकर सवाल पूछें',
  'chat.stopRecording': 'रिकॉर्डिंग रोकें',
  'chat.transcribing': 'आपकी रिकॉर्डिंग लिखी जा रही है\u2026',
  'chat.transcriptReview': 'भेजने से पहले लिखा हुआ देखें। बदल भी सकते हैं।',
  'chat.detectedLanguage': 'पहचानी गई भाषा: {language}',
  'chat.detectionUnclear': 'बोली गई भाषा पहचान नहीं पाई। नीचे चुनें ताकि सही आवाज़ में जवाब मिले।',
  'chat.spokenLanguage': 'आपने जिस भाषा में बोला',
  'chat.useInterfaceLanguage': 'इंटरफ़ेस भाषा के समान',
  'chat.chooseLanguage': 'आपने जिस भाषा में बोला, वह चुनें',
  'chat.pickLanguageBeforeSending': 'भेजने से पहले बोली गई भाषा चुनें, ताकि जवाब और आवाज़ सही हों।',
  'chat.replyLanguage': 'जवाब की भाषा',
  'chat.detectedFromScript': 'लिपि से पहचाना: {language}',
  'chat.followInterfaceLanguage': 'इंटरफ़ेस भाषा का पालन करें',
  'chat.waitingForReply': 'दुकान के सहायक का जवाब आ रहा है\u2026',
  'chat.sendFailedRetry': 'भेजा नहीं गया। आपका सवाल यहीं है - फिर से भेजें।',
  'chat.useTranscript': 'यह सवाल भेजें',
  'chat.speakReply': 'जवाब सुनें',
  'chat.stopSpeaking': 'रोकें',
  'chat.speaking': 'चल रहा है\u2026',
  'chat.guestNote': 'आप मेहमान के रूप में बात कर रहे हैं। बातचीत इसी डिवाइस पर रहेगी।',
  'chat.assistantUnavailable': 'सहायक अभी उपलब्ध नहीं है। फिर कोशिश करें या सीधे दुकान से संपर्क करें।',
  'chat.voiceNotConfigured': 'इस सर्वर पर आवाज़ इनपुट अभी चालू नहीं है। कृपया सवाल लिखें।',
  'chat.micDenied': 'माइक्रोफ़ोन की अनुमति नहीं मिली। ब्राउज़र सेटिंग में अनुमति दें, या सवाल लिखें।',
  'chat.playbackFailed': 'आवाज़ में नहीं चला। लिखा हुआ जवाब ऊपर मौजूद है।',
  'chat.proposedItems': 'सहायक ने ये उत्पाद सुझाए। कार्ट में देख लें।',
  'chat.addProposal': 'कार्ट में जोड़ें',
  'chat.notOrderable': 'ऑर्डर नहीं किया जा सकता',
  'chat.feedbackPrompt': 'क्या यह मददगार रहा?',
  'chat.feedbackThanks': 'प्रतिक्रिया के लिए धन्यवाद।',
  'chat.feedbackComment': 'कुछ और बताना चाहेंगे? (वैकल्पिक)',

  'cart.title': 'आपका कार्ट',
  'cart.empty': 'कार्ट खाली है। सूची से उत्पाद जोड़ें।',
  'cart.itemCount': '{count} उत्पाद',
  'cart.subtotal': 'उप-कुल',
  'cart.checkout': 'देखें और पुष्टि करें',
  'cart.clear': 'कार्ट खाली करें',
  'cart.availabilityWarning': 'कुछ उत्पाद अभी ऑर्डर नहीं हो सकते।',
  'cart.priceFromShop': 'कीमतें दुकान से आती हैं और सर्वर उन्हें जाँचता है।',

  'checkout.title': 'अपना ऑर्डर पुष्ट करें',
  'checkout.fulfillment': 'कैसे लेना चाहेंगे?',
  'checkout.pickup': 'दुकान से पिकअप',
  'checkout.delivery': 'घर डिलीवरी',
  'checkout.name': 'आपका नाम',
  'checkout.email': 'ऑर्डर अपडेट का ईमेल',
  'checkout.phone': 'संपर्क फ़ोन नंबर',
  'checkout.phoneHint': 'ज़रूरत पड़ने पर दुकान इस नंबर पर फ़ोन करेगी।',
  'checkout.address': 'डिलीवरी का पता',
  'checkout.addressHint': 'मकान, गली, लैंडमार्क और पिन कोड।',
  'checkout.notes': 'दुकान के लिए टिप्पणी',
  'checkout.notesHint': 'जैसे: शाम 6 बजे के बाद भेजें।',
  'checkout.optInEmail': 'ऑर्डर की स्थिति बदलने पर ईमेल करें',
  'checkout.confirm': 'ऑर्डर अनुरोध भेजें',
  'checkout.confirming': 'आपका ऑर्डर भेजा जा रहा है\u2026',
  'checkout.noPayment': 'ऐप में कोई भुगतान नहीं लिया जाता। भुगतान सीधे दुकान को करें।',
  'checkout.signInRequired': 'यह ऑर्डर भेजने के लिए Google से साइन इन करें। कार्ट सुरक्षित रहेगा।',
  'checkout.success': '{business} को ऑर्डर अनुरोध भेजा गया।',
  'checkout.successNote': 'दुकान आपका ऑर्डर पुष्ट करेगी। स्थिति ऑर्डर पेज पर देख सकते हैं।',
  'checkout.emailSent': 'दुकान को सूचना ईमेल भेजा गया।',
  'checkout.emailSkipped': 'दुकान ने ऑर्डर ईमेल चालू नहीं किया, इसलिए कोई ईमेल नहीं गया। ऑर्डर ऐप में सेव है।',
  'checkout.emailFailed': 'ऑर्डर सेव है, पर सूचना ईमेल नहीं भेजा जा सका।',
  'checkout.viewOrder': 'ऑर्डर देखें',

  'orders.title': 'आपके ऑर्डर',
  'orders.orderCode': 'ऑर्डर {code}',
  'orders.placedOn': '{date} को दिया',
  'orders.statusHistory': 'स्थिति का इतिहास',
  'orders.items': 'उत्पाद',
  'orders.contactShop': 'दुकान से संपर्क करें',
  'orders.reviewOrder': 'इस ऑर्डर को रेटिंग दें',
  'orders.reviewSubmitted': 'धन्यवाद। आपकी समीक्षा दुकान देख सकेगी।',
  'orders.reviewLocked': 'दुकान ऑर्डर पूरा करने पर आप समीक्षा दे सकेंगे।',
  'orders.alreadyReviewed': 'आप इस ऑर्डर की समीक्षा दे चुके हैं।',
  'orders.rating': 'रेटिंग',
  'orders.comment': 'टिप्पणी',
  'orders.tags': 'क्या अच्छा लगा?',
  'orders.submitReview': 'समीक्षा भेजें',
  'orders.refreshHint': 'हर बार यह पेज खोलने पर स्थिति नई लोड होती है।',

  'status.NEW': 'नया',
  'status.ACCEPTED': 'स्वीकृत',
  'status.PREPARING': 'तैयार हो रहा',
  'status.READY_FOR_PICKUP': 'पिकअप के लिए तैयार',
  'status.OUT_FOR_DELIVERY': 'डिलीवरी के लिए निकला',
  'status.COMPLETED': 'पूरा',
  'status.CANCELLED': 'रद्द',

  'tag.PRODUCT_QUALITY': 'उत्पाद की गुणवत्ता',
  'tag.COMMUNICATION': 'संवाद/सेवा',
  'tag.PACKAGING': 'पैकेजिंग',
  'tag.VALUE': 'कीमत के अनुसार मूल्य',
  'tag.DELIVERY_PICKUP': 'डिलीवरी/पिकअप',

  'account.title': 'आपका खाता',
  'account.profile': 'प्रोफ़ाइल',
  'account.recentStores': 'हाल में देखी दुकानें',
  'account.recentNote': 'आपके खाते में सेव, इसलिए सभी डिवाइस पर मिलती हैं।',
  'account.emailUpdates': 'ऑर्डर अपडेट ईमेल',
  'account.emailUpdatesHint': 'हम सिर्फ़ आपके ऑर्डर के बारे में ईमेल करते हैं।',
  'account.phone': 'फ़ोन नंबर',
  'account.saved': 'आपकी जानकारी सेव हो गई।',
  'account.noOrders': 'अभी कोई ऑर्डर नहीं। शुरू करने के लिए दुकानें देखें।',

  'merchant.setupTitle': 'अपने व्यवसाय की जानकारी दें',
  'merchant.setupIntro': 'ये सब बाद में व्यवसाय टैब से बदल सकते हैं।',
  'merchant.businessName': 'व्यवसाय का नाम',
  'merchant.ownerName': 'मालिक का नाम',
  'merchant.primaryCategory': 'मुख्य श्रेणी',
  'merchant.chooseCategory': 'श्रेणी चुनें',
  'merchant.addressLine': 'दुकान का पता',
  'merchant.addressHint': 'गली, मकान या पास का लैंडमार्क।',
  'merchant.city': 'शहर या कस्बा',
  'merchant.state': 'राज्य',
  'merchant.pincode': 'पिन कोड',
  'merchant.publicPhone': 'सार्वजनिक फ़ोन नंबर',
  'merchant.publicPhoneHint': 'ग्राहक इसे देखेंगे। खाते का ईमेल निजी रखें।',
  'merchant.locationPin': 'लोकेशन पिन',
  'merchant.locationPinHint': 'वैकल्पिक। सटीक जगह दिखानी हो तो निर्देशांक भरें।',
  'merchant.useMyLocation': 'मेरी वर्तमान लोकेशन लें',
  'merchant.locationCaptured': 'लोकेशन मिल गई। नीचे के अंक बदल भी सकते हैं।',
  'merchant.locationDenied': 'लोकेशन की अनुमति नहीं मिली। पता लिखें - पिन वैकल्पिक है।',
  'merchant.locationUnsupported': 'यह ब्राउज़र लोकेशन नहीं दे सकता। पता लिखें - पिन वैकल्पिक है।',
  'merchant.latitude': 'अक्षांश',
  'merchant.longitude': 'देशांतर',
  'merchant.createBusiness': 'मेरा व्यवसाय बनाएँ',
  'merchant.noBusiness': 'इस खाते से अभी कोई व्यवसाय जुड़ा नहीं है।',
  'merchant.createBusinessCta': 'व्यवसाय शुरू करें',
  'merchant.overview': 'व्यवसाय सारांश',
  'merchant.needsAttention': 'ध्यान चाहिए',
  'merchant.newOrders': 'नए ऑर्डर',
  'merchant.openConversations': 'खुले ग्राहक सवाल',
  'merchant.nothingNeedsAttention': 'अभी किसी बात पर ध्यान देने की ज़रूरत नहीं।',
  'merchant.inProgress': 'चल रहे ऑर्डर',
  'merchant.completedOrders': 'पूरे हुए ऑर्डर',
  'merchant.topProducts': 'लोकप्रिय उत्पाद',
  'merchant.topProductsHint': 'पूरे हुए ऑर्डर से गणना।',
  'merchant.topProductsEmpty': 'अभी कोई पूरा ऑर्डर नहीं, इसलिए सूची नहीं।',
  'merchant.recentReviews': 'हाल की रेटिंग और टिप्पणियाँ',
  'merchant.avgRating': 'औसत रेटिंग',
  'merchant.reviewSourceOrder': 'ऑर्डर समीक्षा',
  'merchant.reviewSourceConversation': 'बातचीत की प्रतिक्रिया',
  'merchant.availabilityBreakdown': 'सूची की उपलब्धता',
  'merchant.recentOrders': 'हाल के ऑर्डर',

  'merchant.orders': 'ऑर्डर',
  'merchant.filterStatus': 'स्थिति से फ़िल्टर',
  'merchant.updateStatus': 'स्थिति बदलें',
  'merchant.statusUpdated': 'स्थिति बदलकर {status} हो गई।',
  'merchant.customerDetails': 'ग्राहक और वितरण',
  'merchant.customerName': 'ग्राहक',
  'merchant.customerPhone': 'फ़ोन',
  'merchant.customerEmail': 'ईमेल',
  'merchant.fulfillment': 'वितरण प्रकार',
  'merchant.deliveryAddress': 'डिलीवरी का पता',
  'merchant.statusNote': 'इतिहास के लिए टिप्पणी (वैकल्पिक)',
  'merchant.nextStatuses': 'अगले संभावित चरण',
  'merchant.noNextStatuses': 'यह ऑर्डर बंद है, अब बदला नहीं जा सकता।',
  'merchant.emailSentCustomer': 'इस बदलाव का ईमेल ग्राहक को भेजा गया।',
  'merchant.emailSkippedCustomer': 'ग्राहक ने ऑर्डर ईमेल चालू नहीं किया, इसलिए ईमेल नहीं गया।',

  'merchant.products': 'उत्पाद',
  'merchant.addProduct': 'उत्पाद जोड़ें',
  'merchant.editProduct': 'उत्पाद संपादित करें',
  'merchant.productName': 'उत्पाद का नाम',
  'merchant.productPrice': 'कीमत (₹)',
  'merchant.productAvailability': 'उपलब्धता',
  'merchant.productDescription': 'विवरण',
  'merchant.productCategory': 'श्रेणी',
  'merchant.productAliases': 'वैकल्पिक नाम',
  'merchant.productAliasesHint': 'ग्राहक जिन दूसरे नामों से खोजते हैं, कॉमा से लिखें। जैसे: atta, aata।',
  'merchant.availabilityAvailable': 'उपलब्ध',
  'merchant.availabilityOutOfStock': 'स्टॉक में नहीं',
  'merchant.availabilityUnknown': 'पता नहीं',
  'merchant.availabilityUnknownHint': 'जाँच न की हो तो "पता नहीं" रखें। इसे कभी "उपलब्ध" नहीं दिखाया जाता।',
  'merchant.importExport': 'आयात और निर्यात',
  'merchant.importIntro': 'टेम्पलेट डाउनलोड कर भरें और अपलोड करें। बाद में ऐप से उपलब्धता बदल सकते हैं।',
  'merchant.downloadTemplate': 'XLSX टेम्पलेट डाउनलोड करें',
  'merchant.downloadTemplateCsv': 'CSV टेम्पलेट डाउनलोड करें',
  'merchant.exportProducts': 'मौजूदा सूची निर्यात करें',
  'merchant.exportCsv': 'CSV के रूप में निर्यात',
  'merchant.chooseFile': '.xlsx या .csv फ़ाइल चुनें',
  'merchant.preview': 'सेव करने से पहले जाँचें',
  'merchant.previewIntro': 'आपकी पुष्टि तक कुछ सेव नहीं होता।',
  'merchant.rowsValid': '{count} पंक्तियाँ तैयार',
  'merchant.rowsInvalid': '{count} पंक्तियों में गलती',
  'merchant.rowErrors': 'ठीक करने योग्य गलतियाँ',
  'merchant.rowWarnings': 'चेतावनी',
  'merchant.rowPreview': 'पंक्ति झलक',
  'merchant.rowPreviewHint': 'जो सेव नहीं करना चाहते, उसका टिक हटा दें। सिर्फ़ टिक किए गए पंक्ति सेव होंगे।',
  'merchant.includeRow': 'शामिल करें',
  'merchant.importSavedSkipped': 'सेव हुआ: {created} जोड़े, {updated} अपडेट, {skipped} छोड़े।',
  'merchant.confirmImport': '{count} उत्पाद सेव करें',
  'merchant.importSaved': 'सेव हुआ: {created} जोड़े, {updated} अपडेट।',
  'merchant.importNothingSaved': 'फ़ाइल में गलतियाँ होने से कुछ सेव नहीं हुआ।',
  'merchant.importEmpty': 'फ़ाइल में कोई उत्पाद पंक्ति नहीं।',
  'merchant.archived': 'संग्रहित',
  'merchant.showArchived': 'संग्रहित दिखाएँ',
  'merchant.productArchived': 'उत्पाद संग्रहित। ग्राहक अब नहीं देखेंगे।',
  'merchant.productRestored': 'उत्पाद वापस लाया गया।',

  'merchant.businessProfile': 'व्यवसाय प्रोफ़ाइल',
  'merchant.publicDetails': 'सार्वजनिक जानकारी',
  'merchant.storeHours': 'दुकान का समय',
  'merchant.day': 'दिन',
  'merchant.closed': 'बंद',
  'merchant.opens': 'खुलता है',
  'merchant.closes': 'बंद होता है',
  'merchant.copyMonday': 'सोमवार का समय सभी दिनों में डालें',
  'merchant.storeInfo': 'सहायक के लिए दुकान की जानकारी',
  'merchant.assistantNotes': 'सहायक के लिए अतिरिक्त जानकारी',
  'merchant.assistantNotesHint': 'जैसे: रोज़ सुबह सब्ज़ी आती है। जानकारी सच्ची रखें।',
  'merchant.deliveryNotes': 'डिलीवरी विवरण',
  'merchant.paymentMethods': 'स्वीकृत भुगतान',
  'merchant.paymentMethodsHint': 'हर पंक्ति में एक। केवल जानकारी; भुगतान प्रोसेस नहीं होता।',
  'merchant.returnPolicy': 'वापसी नीति',
  'merchant.faqs': 'अक्सर पूछे जाने वाले सवाल',
  'merchant.addFaq': 'सवाल जोड़ें',
  'merchant.faqQuestion': 'सवाल',
  'merchant.faqAnswer': 'जवाब',
  'merchant.notifications': 'ईमेल सूचनाएँ',
  'merchant.notifyNewOrders': 'नया ऑर्डर आने पर ईमेल करें',
  'merchant.notifyEmail': 'सूचना ईमेल पता',
  'merchant.notifyEmailHint': 'चाहें तो लॉगिन ईमेल से अलग रखें।',
  'merchant.visibility': 'दृश्यता',
  'merchant.isActive': 'व्यवसाय सक्रिय',
  'merchant.isPublic': 'ग्राहक सूची में दिखाएँ',
  'merchant.saved': 'आपके बदलाव सेव हो गए।',
  'merchant.noEmailConfigured': 'इस सर्वर पर ईमेल भेजना चालू नहीं, इसलिए सूचना नहीं भेजी जा सकती।',

  'merchant.conversations': 'ग्राहक के सवाल',
  'merchant.markResolved': 'सुलझा हुआ चिह्नित करें',
  'merchant.markOpen': 'फिर खोलें',
  'merchant.guestCustomer': 'मेहमान ग्राहक',
  'merchant.conversationFeedback': 'बातचीत की प्रतिक्रिया',

  'error.network': 'सर्वर तक नहीं पहुँच सके। कनेक्शन देखकर फिर कोशिश करें।',
  'error.notFound': 'यह पेज नहीं मिला।',
  'error.forbidden': 'इसकी आपको अनुमति नहीं है।',
  'error.validation': 'चिह्नित फ़ील्ड देख लें।',
};

export const STRINGS: Record<'en' | 'bn' | 'hi', Table> = {
  en: en as unknown as Table,
  bn,
  hi,
};
